[package]
name = "pollnet"
version = "0.1.0"
authors = ["probable-basilisk <basilisk@mtknn.com>"]
edition = "2018"

[dependencies]
tokio-tungstenite = {version = "*", features = ["tls"]}
tungstenite = {version = "*", features = ["tls"]}
futures = "*"
url = "*"
futures-util = "*"

[dependencies.tokio]
version = "*"
features = ["sync", "macros"]

[lib]
name = "pollnet"
crate-type = ["cdylib"]